[project]
name = "uv-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "whenever>=0.6.16",
]

[dependency-groups]
dev = [
    "wat",
]
